#!/bin/bash
#==============================================================================
# STM32 项目编译环境设置脚本（跨项目通用）
#
# 用法: source .claude/skills/stm32-build/env.sh
#
# 自动完成以下操作：
#   1. 从 CMakeCache.txt 发现 cmake / ninja / arm-gcc 路径
#   2. 从磁盘搜索 STM32CubeProgrammer CLI 路径
#   3. 从 build 目录发现 ELF 文件名
#   4. 设置 PATH 并切换到项目根目录
#
# 无硬编码路径，可随 .claude/skills/stm32-build/ 目录一起迁移到任意项目。
#==============================================================================

set -euo pipefail

# ---- 项目根目录（skill 目录向上 3 级） ----
PROJECT_ROOT="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]:-$0}")")/../../.." && pwd)"
cd "$PROJECT_ROOT"

# ---- 发现工具链（从 CMakeCache.txt） ----
CMAKE_CACHE="$PROJECT_ROOT/build/Debug/CMakeCache.txt"

if [ ! -f "$CMAKE_CACHE" ]; then
    echo "[env.sh] 错误: 找不到 $CMAKE_CACHE"
    echo "[env.sh] 请先在 VSCode 中运行 CMake Configure（Ctrl+Shift+P → CMake: Configure）"
    return 1 2>/dev/null || exit 1
fi

CMAKE_PATH=$(head -3 "$CMAKE_CACHE" | grep "It was generated by CMake:" | sed 's/.*CMake: //')
CMAKE_BIN="$(dirname "$CMAKE_PATH")"

ADDR2LINE=$(grep "CMAKE_ADDR2LINE:FILEPATH" "$CMAKE_CACHE" | cut -d= -f2)
GCC_BIN="$(dirname "$ADDR2LINE")"

NINJA_PATH=$(grep "CMAKE_MAKE_PROGRAM:FILEPATH" "$CMAKE_CACHE" | cut -d= -f2)
if [ -z "$NINJA_PATH" ]; then
    BUNDLE_BASE="$(dirname "$(dirname "$(dirname "$(dirname "$(dirname "$CMAKE_PATH")")")")")"
    NINJA_PATH=$(ls -d "$BUNDLE_BASE/ninja/"*"/bin/ninja.exe" 2>/dev/null | sort -V | tail -1)
fi
NINJA_BIN="$(dirname "$NINJA_PATH")"

export PATH="$CMAKE_BIN:$NINJA_BIN:$GCC_BIN:$PATH"

# ---- 发现 STM32CubeProgrammer CLI ----
CUBEPROG=""
for drive in /c/ /d/ /e/ /f/; do
    CUBEPROG=$(find "$drive" -maxdepth 5 -name "STM32_Programmer_CLI.exe" -type f 2>/dev/null | head -1)
    [ -n "$CUBEPROG" ] && break
done

# ---- 发现 ELF 文件 ----
ELF_FILE=$(ls "$PROJECT_ROOT/build/Debug/"*.elf 2>/dev/null | head -1 || true)
PROJECT_NAME=$(grep "CMAKE_PROJECT_NAME:STATIC" "$CMAKE_CACHE" 2>/dev/null | cut -d= -f2 || echo "")

# ---- 输出摘要 ----
echo "=========================================="
echo " STM32 编译环境已就绪"
echo "=========================================="
echo " 项目     : $PROJECT_ROOT ($PROJECT_NAME)"
echo " CMake    : $CMAKE_PATH"
echo " Ninja    : $NINJA_PATH"
echo " ARM GCC  : $GCC_BIN"
if [ -n "$CUBEPROG" ]; then
    echo " 烧录工具 : $CUBEPROG"
else
    echo " 烧录工具 : [未找到] 请安装 STM32CubeProgrammer"
fi
echo " ELF      : ${ELF_FILE:-[尚未编译]}"
echo "=========================================="
echo ""
echo " 可用命令："
echo "   cmake --build build/Debug         增量编译"
echo "   cmake --build build/Debug --clean-first  全量重编译"
if [ -n "$CUBEPROG" ] && [ -n "$ELF_FILE" ]; then
    echo "   \"$CUBEPROG\" -c port=SWD -w \"$ELF_FILE\" -v -g   烧录+运行"
fi
echo ""

# 导出变量供后续使用
export CUBEPROG
export ELF_FILE
export PROJECT_ROOT
export PROJECT_NAME
